#!/usr/bin/env bash
# Clipstack Mission Control — one-command local dev setup.
#
# Brings up Postgres, applies migrations, seeds a demo workspace, writes
# .env.local with auth-stub bypass, and tells you to run pnpm dev. Idempotent;
# safe to re-run after schema or seed changes.
#
# Usage (from the approval-ui dir or the repo root):
#   bash services/approval-ui/scripts/dev-setup.sh
#
# Prereqs: docker (for the postgres container), node 20+, pnpm 9+, psql.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
APPROVAL_UI_DIR="$REPO_ROOT/services/approval-ui"
MIGRATIONS_DIR="$REPO_ROOT/services/shared/db/migrations"
COMPOSE_FILE="$REPO_ROOT/docker-compose.yml"

DB_USER="clipstack"
DB_PASS="change-me-locally"
DB_NAME="clipstack"
DB_HOST="localhost"
DB_PORT="5432"
LOCAL_DB_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# These match the seed script's deterministic UUIDs so AUTH_STUB resolves
# to the seeded user + workspace without a WorkOS round-trip.
DEMO_USER_ID="00000000-0000-0000-0000-000000000002"
DEMO_COMPANY_ID="00000000-0000-0000-0000-000000000001"

step() { printf "\n\033[1;36m[setup]\033[0m %s\n" "$*"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$*"; }
warn() { printf "  \033[33m⚠\033[0m %s\n" "$*"; }
die()  { printf "\n\033[31m[setup] %s\033[0m\n" "$*" >&2; exit 1; }

# ─── 1. Prereq checks ──────────────────────────────────────────────────────

step "Checking prerequisites"
command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker Desktop or rancher-desktop."
command -v pnpm >/dev/null 2>&1   || die "pnpm not found. Install: npm i -g pnpm"
command -v psql >/dev/null 2>&1   || die "psql not found. Install postgresql-client."
command -v node >/dev/null 2>&1   || die "node not found. Install Node 20+."

NODE_MAJOR="$(node -v | sed -E 's/v([0-9]+).*/\1/')"
if [ "$NODE_MAJOR" -lt 20 ]; then
  die "Node 20+ required (you have $(node -v))."
fi
ok "docker / pnpm / psql / node $(node -v) all present"

# ─── 2. Postgres container ─────────────────────────────────────────────────

step "Bringing up Postgres (docker compose)"
if ! docker ps --format '{{.Names}}' | grep -q '^clipstack-postgres'; then
  (cd "$REPO_ROOT" && docker compose up -d postgres)
  ok "postgres container started"
else
  ok "postgres container already running"
fi

# Wait for it to accept connections.
step "Waiting for Postgres to be ready"
for i in $(seq 1 30); do
  if PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c 'SELECT 1' >/dev/null 2>&1; then
    ok "postgres reachable on $DB_HOST:$DB_PORT"
    break
  fi
  if [ "$i" -eq 30 ]; then
    die "postgres didn't come up after 30s. Check 'docker compose logs postgres'."
  fi
  sleep 1
done

# ─── 3. Migrations ─────────────────────────────────────────────────────────

step "Applying migrations from $MIGRATIONS_DIR"
shopt -s nullglob
applied=0
for mig in "$MIGRATIONS_DIR"/*.sql; do
  name="$(basename "$mig")"
  # Idempotent: each migration uses CREATE ... IF NOT EXISTS / ALTER ... or
  # its own guard. Re-applying is a no-op for already-applied ones; new ones
  # land. The output below is concise; enable -v for verbose.
  if PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
       -v ON_ERROR_STOP=1 -q -f "$mig" >/dev/null 2>&1; then
    ok "applied $name"
    applied=$((applied + 1))
  else
    # Re-run with output so the user sees which migration broke.
    warn "$name failed — re-running with output:"
    PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
      -v ON_ERROR_STOP=1 -f "$mig" || die "migration $name failed"
  fi
done
shopt -u nullglob
ok "$applied migrations applied"

# ─── 4. Install pnpm deps ──────────────────────────────────────────────────

step "Installing pnpm deps"
(cd "$APPROVAL_UI_DIR" && pnpm install --silent)
ok "deps installed"

# ─── 5. Run seed (the seed script handles its own idempotency) ─────────────

step "Seeding demo workspace"
export DATABASE_URL="$LOCAL_DB_URL"
(cd "$APPROVAL_UI_DIR" && pnpm exec tsx scripts/seed-demo.ts) || die "seed-demo failed"

# ─── 6. Write .env.local with AUTH_STUB bypass ─────────────────────────────

step "Writing $APPROVAL_UI_DIR/.env.local (AUTH_STUB bypass for local dev)"
ENV_LOCAL="$APPROVAL_UI_DIR/.env.local"
SESSION_PWD="$(openssl rand -base64 48 | tr -d '=+/' | cut -c1-64)"

cat > "$ENV_LOCAL" <<ENVEOF
# Generated by services/approval-ui/scripts/dev-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Local-dev only. Re-run dev-setup.sh to regenerate.

NODE_ENV=development
DATABASE_URL=$LOCAL_DB_URL

# AUTH_STUB bypasses WorkOS so you can poke at the UI without the OAuth
# round-trip. Refused at NODE_ENV=production by lib/api/auth.ts. The IDs
# here resolve to the seeded "Demo User" + "Demo Workspace".
AUTH_STUB_USER_ID=$DEMO_USER_ID
AUTH_STUB_COMPANY_ID=$DEMO_COMPANY_ID

# Iron-session cookie key. Random per setup so you can't accidentally
# reuse a key across machines. Don't commit .env.local.
SESSION_COOKIE_PASSWORD=$SESSION_PWD

# Backend service URLs left empty — Mission Control's tiles fail-soft
# (empty data, "service unreachable" indicators) when these are unset.
# Set them when you bring up the python services via docker compose.
BANDIT_ORCH_BASE_URL=
PERFORMANCE_INGEST_BASE_URL=
AGENT_LANGGRAPH_BASE_URL=
AGENT_CREWAI_BASE_URL=
PII_DETECTION_BASE_URL=
OUTPUT_MODERATION_BASE_URL=
VOICE_SCORER_BASE_URL=
PERCENTILE_PREDICTOR_BASE_URL=

# Service-token for cross-service auth. Empty in local dev = stub-mode
# fallbacks return [] / skipped=true.
SERVICE_TOKEN=
ENVEOF
chmod 600 "$ENV_LOCAL"
ok "wrote $ENV_LOCAL (chmod 600)"

# ─── 7. Done ───────────────────────────────────────────────────────────────

cat <<DONEEOF

\033[1;32m[setup] Done.\033[0m

To start Mission Control:

  cd $APPROVAL_UI_DIR
  pnpm dev

Then open http://localhost:3000.

You'll land on Mission Control logged in as the Demo User in the
"Demo Workspace" tenant — populated by the seed script with:
  • 12 drafts (4 awaiting approval, 4 published, mix of others)
  • 30 audit-log rows over the last 7d
  • 8 captured editorial lessons
  • 40 metric snapshots driving the KPI tiles
  • 6 agents (1 working, 1 blocked, 4 idle)

Pages to visit:
  /                                — Mission Control bento
  /inbox                           — pending-approval queue
  /drafts/<draft-id>               — draft body + metric history (click any
                                     row in /inbox or the queue tile)
  /experiments                     — bandits list (empty until orchestrator
                                     ships state — running this stack is
                                     out of scope for the seed)
  /activity                        — audit-log feed
  /performance?range=7d            — workspace KPI history
  /workspace, /calendar, /members,
  /settings                        — placeholder pages

To reset: re-run this script. The seed deletes-then-inserts the demo
tenant so it's safe to run repeatedly.

DONEEOF
